dist: xenial
language: python
cache: pip

matrix:
  include:
    - env: TOXENV=lint
      python: 3.6
    - env: TOXENV=py36-md32
      python: 3.6
    - env: TOXENV=py38-md32
      python: 3.8

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
