name: ci

on: pull_request

jobs:

  unittests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        toxenv:
            - py36-md32
            - py38-md32
        include:
          - toxenv: py36-md32
            python-version: 3.6
          - toxenv: py38-md32
            python-version: 3.8

    steps:
      - uses: actions/checkout@v2

      - name: Fetch tags and commits needed for setuptools-git-version
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch origin ${{ github.head_ref }} && git checkout ${{ github.head_ref }}
          git describe --tags --long --dirty
        # If the above git describe command doesn't work,
        # then setuptools-git-version will also fail.

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox coveralls

      - name: Run tox
        run: |
          tox
          coveralls
        env:
          TOXENV: ${{ matrix.toxenv }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
